# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
# permalink:        pretty
# relative_permalinks: true

# Setup
title:            Mekana Giriş
tagline:          'A Jekyll Mekan'
description:      ''
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Musa Kasım'
  url:            https://github.com/musakasim

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/musakasim
